/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { Canvas, useFrame } from "@react-three/fiber";

export default function Model(props) {
  const group = useRef();

  useFrame(({ clock }) => {
    const a = clock.getElapsedTime() / 4;
    group.current.rotation.y = a;
  });

  const { nodes, materials } = useGLTF("/untitled.gltf");
  return (
    <group {...props} ref={group} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["3D_MNK_A_810_Popiersie_Napoleona1"].geometry}
        material={materials.MAT_Nap}
        rotation={[Math.PI / 2, 0, 0]}
      ></mesh>
    </group>
  );
}

useGLTF.preload("/untitled.gltf");
